logging:
  level:
    org:
      springframework: info

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*' # To enable the web exposure of all management endpoints