logging:
  level:
    org:
      springframework: info

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*' # To enable the web exposure of all management endpoints

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/sports"
    username: admin
    password: passwd
    driver-class-name: org.postgresql.Driver