CREATE TABLE PLAYER
(
    ID          INTEGER      NOT NULL,
    NAME        VARCHAR(255) NOT NULL,
    NATIONALITY VARCHAR(255) NOT NULL,
    BIRTH_DATE  TIMESTAMP,
    TITLE       INTEGER,
    PRIMARY KEY (ID)
);

INSERT INTO Player (ID, NAME, NATIONALITY, BIRTH_DATE, TITLE)
VALUES(1, 'Djokovic', 'SERBIA', '1987-05-22', 81);

INSERT INTO Player (ID, NAME, NATIONALITY, BIRTH_DATE, TITLE)
VALUES(2, 'Messi', 'ARGENTINA', '1986-09-01', 10);

INSERT INTO Player (ID, NAME, NATIONALITY, BIRTH_DATE, TITLE)
VALUES(3, 'Nadal', 'SPAIN', '1985-04-26', 15);